name: flexify
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  page_transition: "^2.1.0"
  fl_chart: ^0.65.0
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  collection: ^1.18.0
  flutter_svg: ^2.0.4
  connectivity_plus: ^5.0.2
  http: ^1.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.jpg"
  adaptive_icon_background: "assets/icon/icon-background.png"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: JosefinSans
      fonts:
        - asset: ./assets/fonts/KronaOne-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
    - family: Sacramento
      fonts:
        - asset: ./assets/fonts/Sacramento-Regular.ttf
  assets:
    - assets/
    - assets/img/
    - assets/Squiggly Arrow.svg
    - assets/icon/
