name: flexify
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  page_transition: "^2.1.0"
  fl_chart: ^0.65.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  collection: ^1.18.0
  flutter_svg: ^2.0.4
  connectivity_plus: ^5.0.2
  http: ^1.1.2
  shared_preferences: ^2.2.2
  percent_indicator: ^4.2.3
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  dio: ^5.4.2
  image_picker: ^1.0.7
  image: ^4.1.7
  multipart_request_null_safety: ^0.3.4
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/appicon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: KronaOne
      fonts:
        - asset: ./assets/fonts/KronaOne-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
    - family: Sacramento
      fonts:
        - asset: ./assets/fonts/Sacramento-Regular.ttf
  assets:
    - assets/

    - assets/img/
    - assets/icon/

    - assets/logo/Dark Logo.svg
    - assets/logo/Light Logo.svg
    - assets/logo/darklogo.png
    - assets/logo/lightlogo.png
    - assets/icon/google.png

    - assets/bodyFatPercentage/male/4-6%.svg
    - assets/bodyFatPercentage/male/7-10%.svg
    - assets/bodyFatPercentage/male/11-15%.svg
    - assets/bodyFatPercentage/male/16-23%.svg
    - assets/bodyFatPercentage/male/23-30%.svg
    - assets/bodyFatPercentage/male/31-40%.svg
    - assets/bodyFatPercentage/male/>40%.svg

    - assets/bodyFatPercentage/female/10-15%.svg
    - assets/bodyFatPercentage/female/16-20%.svg
    - assets/bodyFatPercentage/female/21-25%.svg
    - assets/bodyFatPercentage/female/26-30%.svg
    - assets/bodyFatPercentage/female/31-35%.svg
    - assets/bodyFatPercentage/female/36-45%.svg
    - assets/bodyFatPercentage/female/>45%.svg
